config/routes.rb
Rails.application.routes.draw do
  devise_for :psychologists

  resources :evaluatees, except: %i[destroy] do
    resources :assessments, only: %i[new create show] do
      member do
        get :start
        post :submit
        get :questions
        post :submit_answers
        get :complete
      end
    end
    resources :instruments, except: :delete
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
  devise_scope :psychologist do
    root to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :evaluatee
  belongs_to :instrument
  belongs_to :psychologist
  delegate :questions, to: :instrument
  delegate :name, to: :instrument

  def score
    {
      'Option 1' => 3,
      'Option 2' => 2,
      'Option 3' => 1,
      'Option 4' => 0
    }
  end

  def total_score
    return if responses.empty?

    total_score = 0
    responses.each do |option|
      total_score += score[option] if score[option]
    end
    total_score
  end
end

app/models/evaluatee.rb
class Evaluatee < ApplicationRecord
  belongs_to :psychologist
  has_many :assessments
  has_many :instruments, through: :assessments

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :cpf, presence: true, uniqueness: true, length: { is: 11 }, format: { with: /\A[0-9]+\z/ }
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :assessments
  has_many :evaluatees, through: :assessments

end

app/models/psychologist.rb
class Psychologist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :evaluatees

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    if resource.is_a?(Psychologist)
      evaluatees_path
    else
      new_psychologist_session_path
    end
  end
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :authenticate_psychologist!, except: %i[start submit questions submit_answers complete]
  before_action :set_evaluatee
  before_action :set_assessment, only: %i[start submit questions submit_answers complete show]

  def new
    @assessment = @evaluatee.assessments.build
    @instruments = Instrument.all
  end

  def create
    @assessment = @evaluatee.assessments.build(assessment_params)

    if @assessment.save
      redirect_to evaluatee_path(@evaluatee)
      Assessments::SendEmail.run(evaluatee: @evaluatee, assessment_id: @assessment.id)
    else
      @instruments = Instrument.all
      render :new
    end
  end

  def start; end

  def submit
    if @evaluatee.update(evaluatee_params)
      redirect_to questions_evaluatee_assessment_path(@evaluatee, @assessment)
    else
      render :start
    end
  end

  def questions
    @questions = @assessment.questions
  end

  def submit_answers
    @assessment.update(responses: params[:choice_ids], status: :finalized)
    if @assessment.save
      redirect_to complete_evaluatee_assessment_path(@evaluatee, @assessment)
    else
      @questions = @assessment.questions
      render :questions
    end
  end

  private

  def set_assessment
    @assessment = Assessment.find(params[:id])
  end

  def set_evaluatee
    @evaluatee = Evaluatee.find(params[:evaluatee_id])
  end

  def assessment_params
    params.require(:assessment).permit(:instrument_id)
          .merge(
            evaluatee_id: @evaluatee.id,
            psychologist_id: current_psychologist.id
          )
  end

  def evaluatee_params
    params.require(:evaluatee).permit(:name, :cpf, :email, :birthdate)
  end
end

app/controllers/evaluatees_controller.rb
class EvaluateesController < ApplicationController
  before_action :authenticate_psychologist!
  before_action :evaluatee, only: [:show]

  def index
    @evaluatees = current_psychologist.evaluatees
  end

  def show; end

  def new
    @evaluatee = Evaluatee.new
  end

  def create
    @evaluatee = Evaluatee.create(permitted_params)
    if @evaluatee.persisted?
      redirect_to action: :index
    else
      render :new
    end
  end

  private

  def permitted_params
    params.require(:evaluatee).permit(
      :name, :email, :cpf, :birthdate
    ).merge(psychologist: current_psychologist)
  end

  def evaluatee
    @evaluatee = current_psychologist.evaluatees.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :authenticate_psychologist!
  before_action :set_evaluatee

  def index
    @instruments = @evaluatee.instruments
  end

  private

  def set_evaluatee
    @evaluatee = Evaluatee.find(params[:evaluatee_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/assessments/complete.html.erb
<!-- app/views/assessments/complete.html.erb -->
<h1>Congratulations! Your answers have been saved.</h1>

app/views/assessments/new.html.erb
<div class="container">
  <div class='card'>
     <h5 class="card-header">
     Apply an Instrument to <%= @evaluatee.name %>
    </h5>
    <div class="card-body">
    <%= simple_form_for [@evaluatee, @assessment] do |f| %>
      <div class="field">
        <%= f.association :instrument, collection: Instrument.all, label_method: :name, value_method: :id, prompt: 'Select an Instrument' %>
      </div>

      <div class="actions">
        <%= f.button :submit,  class: 'btn btn-primary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/assessments/questions.html.erb
<!-- app/views/assessments/questions.html.erb -->
<%= simple_form_for @assessment, url: submit_answers_evaluatee_assessment_path(@evaluatee, @assessment), method: :post do |f| %>
  <% @questions.each do |question| %>
    <div>
      <p><%= question["title"] %></p>
      <% question["options"].each do |choice| %>
        <%= check_box_tag 'choice_ids[]', choice["name"], false %>
        <%= hidden_field_tag 'scores[]', choice["score"] %>
        <%= label_tag 'choice_ids[]', choice["name"] %>
      <% end %>
    </div>
  <% end %>
  <%= f.button :submit, 'Submit',  class: 'btn btn-primary' %>
<% end %>

app/views/assessments/show.html.erb
<div class="container">
  <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
    Instrument Information
  </h1>
  <div class='card'>
    <div class="my-3 p-3">
      <dl class="row">
      <div class="col-md-4">
          <dt>Name</dt>
          <dd><%= @assessment.name %></dd>
          <% if @assessment.status == 'finalized' %>
            <dt>Result</dt>
            <dd><%= @assessment.total_score %> </dd>
          <% end %>
        </div>
      </dl>
    </div>
  </div>
  <div class='card'>
    <div class="my-3 p-3">
      <dl class="row">
      <div class="col-md-4">
        <dt>Instruments Questions</dt>
        <dd>
        <table class="table">
        <thead>
          <tr>
            <th scope="col">Question</th>
            <th scope="col">Option</th>
          </tr>
        </thead>
        <tbody>
          <% @assessment.questions.each do |question| %>
              <tr>
                <td><%= question['title'] %></td>
                <% question['options'].each do |option| %>
                <td><%= option['name'] %></td>
                <% end %>
              </tr>

          <% end %>
        </tbody>
      </table>
        </dd>
      </div>
      </dl>
    </div>
  </div>
</div>

app/views/assessments/start.html.erb
<!-- app/views/assessments/start.html.erb -->
<%= simple_form_for @evaluatee, url: submit_evaluatee_assessment_path(@evaluatee, @assessment), method: :post do |f| %>
  <%= f.input :name, input_html: { value: @evaluatee.name } %>
  <%= f.input :cpf, input_html: { value: @evaluatee.cpf } %>
  <%= f.input :email, input_html: { value: @evaluatee.email } %>
  <%= f.input :birthdate, as: :date, start_year: Time.now.year - 100, end_year: Time.now.year - 18, discard_day: true, selected: @evaluatee.birthdate %>

  <%= f.button :submit, 'Next',  class: 'btn btn-primary' %>
<% end %>

app/views/evaluatees/index.html.erb
<div class="container-fluid">
  <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
      <h1>Evaluatees</h1>
  </h1>
  <section>
    <div class="card">
      <div class="card-body">
        <%= link_to 'Create New Account', new_evaluatee_path, class: 'btn btn-primary' %>
        <table class="table table-hover">
          <thead>
            <th>Evaluatee Name</th>
            <th>Evaluatee Email</th>
            <th>Evaluatee CPF</th>
            <th>Evaluatee Birthdate</th>
            <th></th>
            </thead>
          <tbody>
            <% for evaluatee in @evaluatees do %>
              <tr>
                <td><%= link_to evaluatee.name, evaluatee_path(evaluatee) %></td>
                <td><%= evaluatee.email %></td>
                <td><%= evaluatee.cpf %></td>
                <td><%= evaluatee.birthdate %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</div>

app/views/evaluatees/new.html.erb
<div class="container">
  <div class='card'>
     <h5 class="card-header">
      New Evaluatee
    </h5>
    <div class="card-body">
      <%= simple_form_for @evaluatee do |f| %>
        <%= f.input :name,  required: true, label: 'Name' %>
        <%= f.input :email, required: true %>
        <%= f.input :cpf, required: true, input_html: { maxlength: 11, minlength: 11 } %>
        <%= f.input :birthdate, required: true, start_year: 1700 %>
        <%= f.submit 'Create', class: 'btn btn-primary mt-3' %>
      <% end %>
    </div>
  </div>
</div>

app/views/evaluatees/show.html.erb
<div class="container">
  <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
      Evaluatee Information
  </h1>
  <div class='card'>
    <div class="my-3 p-3">
      <dl class="row">
      <div class="col-md-4">
          <dt>Name</dt>
          <dd><%= @evaluatee.name %></dt>
        </div>
        <div class="col-md-3">
          <dt>CPF</dt>
          <dd><%= @evaluatee.cpf %></dt>
        </div>
        <div class="col-md-3">
          <dt>Email</dt>
          <dd><%= @evaluatee.email %></dt>
        </div>
        <div class="col-md-4">
          <dt>Birthdate</dt>
          <dd><%= @evaluatee.birthdate.strftime('%m/%d/%Y') %></dt>
        </div>
      </dl>
    </div>
  </div>
  <div class='card'>
    <div class="my-3 p-3">
    <dl class="row">
    <div class="col-md-4">
      <dt>Instruments</dt>
      <dt> <%= link_to 'Apply new Instrument', new_evaluatee_assessment_path(@evaluatee), class: 'btn btn-primary' %> </dt>
      <dd>
      <table class="table table-hover">
        <thead>
          <th>Name</th>
          <th>Status</th>
          </thead>
        <tbody>
          <% @evaluatee.assessments.each do |assessment| %>
            <tr>
              <td> <%= assessment.name %> </td>
              <% if assessment.status == 'finalized' %>
              <td> <%= link_to 'finalized', evaluatee_assessment_path(@evaluatee, assessment, status: 'finalized') %> </td>
              <% else %>
                <td> assessment.status%> </td>
              <% end %>
            </tr>
            <% end %>
        </tbody>
      </table>
      </div>
    </dl>
    </div>
  </div>
</div>

app/views/instruments/index.html.erb
<div class="container-fluid">
  <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
    <h1>Instruments for <%= @evaluatee.name %></h1>
  </h1>
  <section>
    <div class="card">
      <div class="card-body">
          <ul>
            <% @instruments.each do |instrument| %>
              <li><%= instrument.name %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Psychology Instruments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="turbo-prefetch" content="false">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="d-flex flex-column h-100">
    <% if current_psychologist %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Menu</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
              <a href="/evaluatees" class="nav-link">List Evaluatees <span class="sr-only"> </span></a>
              </li>
            </ul>
          </div>
        </nav>
    <% end %>
    <!-- Begin page content -->
    <main class="flex-shrink-0">
      <div class="container pb-3">
        <%= yield %>
      </div>
    </main>
  </body>
</html>